export * as food from "./fastfood_FILL0_wght400_GRAD0_opsz48.svg";
export * as entry from "./gate_FILL0_wght400_GRAD0_opsz48.svg";
export * as playground from "./play_shapes_FILL0_wght400_GRAD0_opsz48.svg";
export * as foodcourt from "./restaurant_FILL0_wght400_GRAD0_opsz48.svg";
export * as signpost from "./signpost_FILL0_wght400_GRAD0_opsz48.svg";
export * as store from "./store_FILL0_wght400_GRAD0_opsz48.svg";
export * as scene from "./theater_comedy_FILL0_wght400_GRAD0_opsz48.svg";
export * as wc from "./wc_FILL0_wght400_GRAD0_opsz48.svg";
export * as treangle from "./triangle.svg"
