export const tableColumns = [
    { title: "id" },
    { title: "Наименование" },
    { title: "Англ. Наим." },
    { title: "Отряд" },
    { title: "Род" },
    { title: "Семейство" },
    { title: "Размер" },
    { title: "Место" },
    { title: "Образ жизни" },
    { title: "Еда" },
    { title: "Человек" },
    { title: "Статус" },
    { title: "Происхождение" },
    { title: "Аудио" },
    { title: "Поинт" },
    { title: "QR-code" },
    { title: "иконка" },
    { title: "Ищем" },
    { title: "Предлагаем" },
];
